### ISSUE TITLE
App uninstall without logging out retains session on the chrome browser

### ISSUE THREAD

**Issue by satyajitvure91** [okta/okta-mobile-kotlin#237]
### Describe the bug?

Hello,

Steps to reproduce:
1. Login to the app with web auth flow
2. Uninstall the app without logging out
3. Reinstall the app
4. Click login

The browser still retains the previous session and doesn't ask to enter new user credentials.

### What is expected to happen?

Ask user to enter credentials.

### What is the actual behavior?

Uses the previously saved session from browser and redirects into the app.

### Reproduction Steps?

Steps to reproduce:
1. Login to the app with web auth flow
2. Uninstall the app without logging out
3. Reinstall the app
4. Click login

### SDK Version and Artifact(s) used.

okta mobile kotlin: 1.1.1

**Comment by rajdeepnanua-okta** [comment]
Hi @satyajitvure91 , this is expected behavior. okta-mobile-kotlin uses Chrome custom tabs for handling browser login. This means that the responsibility of handling session is delegated to the system web browser. When uninstalling, the app doesn't have enough time to log out of the browser. This is unfortunately a limitation that I don't believe can be addressed.

**Comment by jiurchuk** [comment]
So the only way to kill the session that is inside the browser is by calling `WebAuthenticationClient.logoutOfBrowser`?
