### ISSUE TITLE
DefaultIdTokenValidator fails validation for an issuer url without path

### ISSUE THREAD

**Issue by KreVa** [okta/okta-mobile-kotlin#97]
### Describe the bug?

If an issuer url looks like "https://example.okta.com" it turns into "https://example.okta.com/" because `OidcEndpoints` has HttpUrl properties.
Then this check throws an exception:
`if (idTokenPayload.iss != endpointsOrNull?.issuer.toString()) {
    throw IdTokenValidator.Error("Invalid issuer.")
}`

### What is expected to happen?

Check is passed. `IdTokenValidator.Error` exception isn't thrown

### What is the actual behavior?

Check is failed. `IdTokenValidator.Error` exception is thrown

### Reproduction Steps?

Use an issuer url like "https://example.okta.com".  
Try to login. I use the Device authorization flow

### SDK Version and Artifact(s) used.

0.2.0-BETA

**Comment by JayNewstrom** [comment]
Nice find, thanks for the feedback. Will fix!

**Comment by JayNewstrom** [comment]
Fixed in #98 

I'll publish the fix as part of the next beta in a month or so. If this is a blocker for you, there are a few work arounds:
- Customize the `IdTokenValidator` via `OidcConfiguration` or `AuthFoundationDefaults` (either make it no op, or copy the fixed version from the associated PR).
- Use the code in `master` via cloning the repo, and gradle composite builds 

PS, thanks for trying the SDK out. Please reach out again if anything else comes up, or if you have any general feedback!
